markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - rational.md
  - math.md

site_name: Vinculum
site_url: https://cariad.github.io/vinculum/

theme:
  name: material
