name: push
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Validate
        run: >
          pip install --upgrade --user -r requirements.dev.txt &&
          ./validate.sh &&
          coverage xml &&
          ./build.sh ${{ github.ref_name }}

      - uses: codecov/codecov-action@v3.1.1
